name: Configurar Protección de Ramas

on:
  push:
    branches:
      - main

jobs:
  protect-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar protección para main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method PUT \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/branches/main/protection \
            -f required_status_checks='{"strict": true, "contexts": []}' \
            -f enforce_admins=true \
            -f required_pull_request_reviews='{"dismiss_stale_reviews": true, "require_code_owner_reviews": false}' \
            -f restrictions='{"users": [], "teams": []}'

      - name: Configurar protección para develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method PUT \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/branches/develop/protection \
            -f required_status_checks='{"strict": true, "contexts": []}' \
            -f enforce_admins=true \
            -f required_pull_request_reviews='{"dismiss_stale_reviews": true, "require_code_owner_reviews": false}' \
            -f restrictions='{"users": [], "teams": []}'
